const test=require('node:test'),assert=require('node:assert/strict'),S=require('../docs/sales-ops-core.js');
function row(){const c={id:'a',company_name:'株式会社テスト',postal_code:'900-0012',address:'那覇市泊1',ceo_name:'代表 一郎',phone:'098-123-4567',phase:'pending',source_data:{sales_ops:{fields:{},relationship:{status:'clear',checked_at:'2026-10-05',checks:['crm','gmail','source_history']},eligibility:{status:'qualified'},contact:{phone_usable:true},facts:[{text:'社員育成に取り組む',status:'verified',source_kind:'official',source_url:'https://example.jp/company',checked_at:'2026-10-05'}]}}};for(const k of ['company_name','postal_code','address','ceo_name','phone'])c.source_data.sales_ops.fields[k]={value:c[k],status:'verified',source_kind:'official',source_url:'https://example.jp/company',excerpt:'公式記載を照合',checked_at:'2026-10-05'};return c;}
test('changed values, stale or future evidence never unlock mailing',()=>{let c=row();assert.deepEqual(S.mailReasons(c,'2026-10-05'),[]);c.ceo_name='別人';assert.ok(S.mailReasons(c,'2026-10-05').length);c=row();assert.ok(S.mailReasons(c,'2026-11-06').length);assert.equal(S.verified(c,'ceo_name','2026-10-04'),false);});
test('stops, missing channel checks and duplicates block export',()=>{const c=row();c.no_solicitation=true;assert.equal(S.selected([c],300,'2026-10-05').length,0);c.no_solicitation=false;c.source_data.sales_ops.relationship.checks=['crm'];assert.equal(S.selected([c],300,'2026-10-05').length,0);const a=row(),b=row();b.id='b';assert.equal(S.selected([a,b],300,'2026-10-05').length,1);});
test('invalid dates and unsupported evidence rejected',()=>{assert.equal(S.day('2026-02-30'),null);assert.equal(S.day('2026-09-31'),null);const c=row();c.source_data.sales_ops.fields.address.source_kind='secondary';assert.equal(S.verified(c,'address','2026-10-05'),false);});
test('call draft requires actual mailing, letter uses sourced fact',()=>{const c=row();assert.throws(()=>S.draft(c,'call','2026-10-05'));assert.match(S.draft(c,'letter','2026-10-05'),/社員育成/);c.source_data.sales_ops.events=[{type:'flyer_sent'}];assert.match(S.draft(c,'call','2026-10-05'),/先日/);});
test('actual meetings deduplicate; rejected or void events never count',()=>{const c=row();c.source_data.sales_ops.events=[{type:'meeting_confirmed',meeting_at:'2026-10-15T10:00:00+09:00',meeting_id:'m1',accepted:true,qualified:true},{type:'meeting_confirmed',meeting_at:'2026-10-15',meeting_id:'m1',accepted:true,qualified:true},{type:'meeting_confirmed',meeting_at:'2026-10-15',meeting_id:'m2',accepted:false,qualified:true},{type:'flyer_sent',occurred_on:'2026-10-05',voided_at:'2026-10-05'}];assert.equal(S.monthly([c],'2026-10').meeting_confirmed,1);assert.equal(S.monthly([c],'2026-10').flyer_sent,0);});
test('random balanced assignment preserves actual callers and stopped companies',()=>{const rows=Array.from({length:11},(_,i)=>({...row(),id:String(i),company_name:'会社'+i,source_data:{dm_mailed:true,sales_ops:{}}}));rows[0].source_data.sales_ops.events=[{id:'call',type:'call',by:'a'}];rows[0].source_data.call_assignee='b';rows[1].no_solicitation=true;const p=S.assignmentPlan(rows,['a','b','c'],()=>0.37);assert.deepEqual(p.locked,[{id:'0',owner:'a'}]);assert.equal(p.changes.length,9);assert.ok(!p.changes.some(x=>x.id==='1'||x.id==='0'));assert.deepEqual(Object.values(p.counts).sort(),[3,3,4]);const q=S.assignmentPlan(rows,['a','b','c','new'],()=>0.8);assert.equal(q.locked[0].owner,'a');assert.ok(q.changes.some(x=>x.owner==='new'));});
test('unknown old caller remains locked and cannot be assigned at random',()=>{const c=row();c.source_data.dm_mailed=true;c.last_called_at='2026-10-01';const p=S.assignmentPlan([c],['a','b']);assert.equal(p.changes.length,0);assert.equal(p.locked[0].owner,'');});
test('call event and mirrored legacy log are counted only once',()=>{const c=row();c.source_data.sales_ops.events=[{id:'same',type:'call',by:'a'}];c.source_data.contact_log=[{event_id:'same',action:'tel_ok',by:'a'}];assert.equal(S.callHistory(c).length,1);});
test('shortlist never sends and excludes mailed, reserved, stopped, contacted and existing route',()=>{const rows=Array.from({length:7},(_,i)=>({...row(),id:String(i),company_name:'会社'+i,city:'那覇市',source_data:{sales_ops:{}}}));rows[0].source_data.dm_mailed=true;rows[1].source_data.sales_ops.mail_selection={batch_id:'old'};rows[2].excluded=true;rows[3].phase='contacted';rows[4].source_data.sales_ops.relationship={status:'existing'};rows[5].city='名護市';rows[5].address='名護市1';assert.deepEqual(S.shortlist(rows).map(x=>x.id),['6']);assert.equal(S.mailed(rows[6]),false);});
