/* Local-only browser fixture. It does not contact the production DB or use real credentials. */
const fs=require('node:fs'),assert=require('node:assert/strict'),S=require('../docs/sales-ops-core');
const day=S.jstDay();
function row(i,mailed=true,verified=true){const c={id:'qa-'+i,company_name:'確認用会社'+i,city:'那覇市',address:'沖縄県那覇市泊1-'+i,postal_code:'900-0012',ceo_name:'確認用代表'+i,phone:'098-123-4567',phase:'pending',excluded:false,no_solicitation:false,last_called_at:null,updated_at:'2026-10-05T00:00:00+00:00',source_data:{sales_ops:{fields:{},relationship:{status:'clear',checked_at:day,checks:['crm','gmail','source_history']},eligibility:{status:'qualified'},contact:{phone_usable:true},facts:[{text:'社員育成に取り組む',status:'verified',source_kind:'official',source_url:'https://example.jp',checked_at:day}],events:[]}}};if(verified)for(const k of ['company_name','postal_code','address','ceo_name','phone'])c.source_data.sales_ops.fields[k]={value:c[k],status:'verified',source_kind:'official',source_url:'https://example.jp',excerpt:'確認用',checked_at:day};if(mailed){c.source_data.dm_mailed=true;c.source_data.call_assignee=i%2?'megu':'hibiki';c.source_data.sales_ops.events=[{id:'sent-'+i,type:'flyer_sent',batch_id:'TENOHIRA-20260930-300',occurred_on:'2026-09-30'}];}return c;}
const records=Array.from({length:300},(_,i)=>row(i));records[0].source_data.sales_ops.call_team={members:['hibiki','megu']};records.push(row(300,false),row(301,false,false));
const mock=`window.qaRows=${JSON.stringify(records)};window.qaRPC=0;window.supabase={createClient(){return {from(){let f=[],u=null,range=null;const q={select(){return q},eq(k,v){f.push(c=>k==='source_data'?JSON.stringify(c[k])===v:c[k]===v);return q},is(k,v){f.push(c=>c[k]==v);return q},order(){return q},range(a,b){range=[a,b];return q},update(v){u=v;return q},single(){return Promise.resolve({data:structuredClone(window.qaRows.filter(c=>f.every(g=>g(c)))[0]),error:null})},then(resolve,reject){let found=window.qaRows.filter(c=>f.every(g=>g(c)));if(u)for(const c of found)Object.assign(c,structuredClone(u));if(range)found=found.slice(range[0],range[1]+1);return Promise.resolve({data:structuredClone(found),error:null}).then(resolve,reject)}};return q},async rpc(name,{p_changes}){for(const x of p_changes){let c=window.qaRows.find(c=>c.id===x.id);if(JSON.stringify(c.source_data??null)!==JSON.stringify(x.expected_source))return {error:{message:'衝突'},data:null}}for(const x of p_changes){let c=window.qaRows.find(c=>c.id===x.id);c.source_data=structuredClone(x.source_data);c.updated_at=new Date().toISOString()}window.qaRPC++;return {data:p_changes.length,error:null}}}}};`;
let html=fs.readFileSync('docs/attack-list.html','utf8').replace(/<script src="https:\/\/cdn.jsdelivr.net\/npm\/@supabase\/supabase-js@2"><\/script>/,`<script>${mock}</script>`).replace(/pass:\s*'[^']*'/g,"pass:'qa-only'").replace(/const SB_URL =[^\n]*/,'const SB_URL = "https://example.invalid";').replace(/const SB_KEY =[^\n]*/,'const SB_KEY = "qa";');

const {JSDOM,VirtualConsole}=require('jsdom');const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(html,{url:'http://qa.invalid/attack-list.html',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.structuredClone=structuredClone;Object.defineProperty(w,'crypto',{value:require('node:crypto').webcrypto});w.confirm=()=>true;w.HTMLElement.prototype.scrollIntoView=function(){};}});const w=dom.window,d=w.document;
for(const file of ['sales-ops-core.js','sales-ops.js']){const script=d.createElement('script');script.textContent=fs.readFileSync('docs/'+file,'utf8');d.body.append(script);}
function input(id,v){d.getElementById(id).value=v;}function click(text){const b=[...d.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(b,text);b.click();}async function until(f){for(let i=0;i<200;i++){if(f())return;await new Promise(r=>setTimeout(r,10));}throw Error('timed out')}
(async()=>{
input('l-name','mage');input('l-pass','qa-only');d.querySelector('.l-btn').click();await until(()=>d.getElementById('so-results'));click('この300社を見る');assert.match(d.querySelector('.so-result-count').textContent,/表示\s*300社/);assert.equal(d.querySelectorAll('.so-company').length,300);
input('q','確認用会社299');w.eval('renderList()');assert.match(d.querySelector('.so-result-count').textContent,/表示\s*1社/);w.eval("soSetIdentity('megu')");assert.equal(d.querySelectorAll('.so-company').length,150);
d.querySelector('.so-company-actions button').click();input('so-call-outcome','callback');input('so-call-note','確認用の電話結果');input('so-call-next',day);input('so-call-next-action','総務へ再電話');d.getElementById('so-call-done').checked=true;click('電話結果と次回対応を保存');await until(()=>w.qaRows.some(c=>c.source_data.sales_ops.call_owner==='megu'));await until(()=>!w.eval('soBusy'));const locked=w.qaRows.find(c=>c.source_data.sales_ops.call_owner==='megu').id;w.eval('closeModal()');input('so-members','hibiki\nmegu\n新人');click('担当者を保存して、未着手を振り分け直す');await until(()=>w.qaRows.some(c=>c.source_data.call_assignee==='新人'));await until(()=>!w.eval('soBusy'));assert.equal(w.qaRows.find(c=>c.id===locked).source_data.call_assignee,'megu');
click('次に送る300社を選ぶ');await until(()=>w.qaRows.filter(c=>c.source_data.sales_ops.mail_selection).length===2);await until(()=>!w.eval('soBusy'));assert.equal(d.querySelectorAll('.so-company').length,2);click('選んだ会社を郵送準備完了にする');assert.match(d.querySelector('.so-error').textContent,/1社/);assert.equal(d.querySelector('#so-batch-editor .so-primary').disabled,true);w.eval("soPick('qa-301',false)");click('選んだ会社を郵送準備完了にする');d.getElementById('so-bulk-confirm').checked=true;click('1社の準備完了を保存');await until(()=>w.qaRows.find(c=>c.id==='qa-300').source_data.dm_ready);await until(()=>!w.eval('soBusy'));
w.eval('soPickAll(true)');click('選んだ会社を発送完了にする');d.getElementById('so-bulk-confirm').checked=true;click('1社の発送完了を保存');await until(()=>w.qaRows.find(c=>c.id==='qa-300').source_data.dm_mailed);await until(()=>!w.eval('soBusy'));assert.ok(w.qaRows.find(c=>c.id==='qa-300').source_data.call_assignee);assert.equal(w.qaRows.filter(c=>c.source_data.dm_mailed).length,301);assert.equal(w.qaRows.find(c=>c.id===locked).source_data.call_assignee,'megu');assert.deepEqual(errors,[]);console.log('PASS DOM integration: 300 view, search count, own 150, call outcome, fixed caller, new member, saved selection, blocked unverified prep, prepare/send, automatic assignment. Production writes: 0.');dom.window.close();})().catch(e=>{console.error(e,errors);dom.window.close();process.exit(1)});
